### ISSUE TITLE
패키지 스캐폴딩

### ISSUE THREAD

**Issue by Stdev17** [Team-StarGarden/crosstoria-engine#4]
지금 @park012241 님께서 처음으로 스캐폴딩을 하고 계시니까
결과 보고 각자에 맞춰 쓰면 될듯?

**Comment by Alex4386** [comment]
Issue Resolved?

**Comment by park012241** [comment]
I think it should be more
________________________________

**Comment by park012241** [comment]
스캐폴딩 완료하였습니다.
